---
abstract: 'Bundle for Biodiverse dependencies for non-GUI use'
author:
  - 'Shawn Laffan (shawn.laffan@unsw.edu.au)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bundle-BiodiverseNoGUI
no_index:
  directory:
    - t
    - inc
requires:
  Clone: 0
  DBD::XBase: 0
  Data::DumpXML: 0
  Devel::Symdump: 0
  Exception::Class: 0
  Exporter::Easy: 0
  File::BOM: 0
  Geo::Converter::dms2dd: 0
  HTML::QuickTable: 0
  MRO::Compat: 0
  Math::Polygon: 0
  Math::Random::MT::Auto: 0
  PadWalker: 0
  Readonly: 0
  Regexp::Common: 0
  Statistics::Descriptive: 3.02
  Text::CSV_XS: 0.60
  Text::Wrapper: 0
  URI::Escape::XS: 0
  YAML::Syck: 0
  lib: 0
  mylib: 0
  parent: 0
version: 0.16
